### PR TITLE
Create Why Use Hourly Contracts

### PR DESCRIPTION
**Pull request by vincetibone**
@pwidry15 @t20rex 

Sorry for the 2nd note, but I figured out how to do the pull request correctly this time.

Please provide feedback on my first draft and each suggest a way for me to improve my contribution.

Thanks!

Vince

### CODE REVIEW

**Comment by pwidry15** [comment]
Vince, I would perhaps integrate a line or two about how hiring a trusted team rather than an individual may affect your decision of whether to hire hourly or per project.

**Comment by vincetibone** [comment]
@t20rex Alex, can you please suggest an improvement to my takeaway sometime today. I would really appreciate it as I am going out of town tomorrow and am hoping to merge my section before I leave if possible.

Thanks! Vince

**Comment by t20rex** [comment]
Hey Vince!

Thank you for your email!
I will definitely upload comments on github before 3:00. Would it be ok
with you?! Sorry am at EMI studio now. Sorry for the delay bro! I have been
catching up with github since yesterday.

Thank you Vince

Best,
Alex

2015년 4월 23일 목요일, vincetibonenotifications@github.com님이 작성한 메시지:

**Comment by vincetibone** [comment]
That'd be great thanks. I just want to make sure you get credit for this assignment by giving feedback on our posts

**Comment by vincetibone** [comment]
@pwidry15 @t20rex Thank you for your feedback. 

Please see the updated version with your comments incorporated. Give me a :+1: if this is good to ship.

Thanks! Vince

**Comment by pwidry15** [comment]
+1...looks good.

**Comment by pwidry15** [comment]
:+1:

**Comment by pwidry15** [comment]
That's what I meant...

**Pull request merged**
